# Generated by Django 5.2.10 on 2026-02-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedwebsite',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
