# Generated by Django 5.2.10 on 2026-02-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trackedwebsite_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedwebsite',
            name='last_scraped',
            field=models.DateTimeField(null=True),
        ),
    ]
