# Generated by Django 5.2.10 on 2026-02-06 10:28

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trackedwebsite_notify_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedWebsiteSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_url', models.URLField(blank=True)),
                ('status_code', models.PositiveIntegerField(null=True)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('html_file', models.FileField(upload_to=api.models.snapshot_upload_path)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.trackedwebsite')),
            ],
        ),
    ]
