# Generated by Django 5.2.10 on 2026-02-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trackedwebsitesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedwebsite',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
