# Generated by Django 5.2.10 on 2026-02-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trackedwebsite_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedwebsite',
            name='notify_sms',
        ),
    ]
