# Generated by Django 5.2.10 on 2026-02-09 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_trackedwebsite_notify_sms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trackedwebsite',
            constraint=models.UniqueConstraint(fields=('owner', 'url'), name='uniq_owner_url'),
        ),
    ]
